### ISSUE TITLE
Vertical Navigation invisible when going to Dashboard from "Download Extras" or "Media Browser"

### ISSUE THREAD

**Issue by mcnickel** [meltingmedia/Vertical-Navigation#3]
Left Navigation stays collabsed when going to Dashboard from "Package Management"/"Download Extras" or "Media Browser". When moving the splitbar only the background shows up, without the Vertical Navigation.

MODX 2.3.3, PHP 5.4.3

Very useful extra! Guess many will prefer it to the standard.

**Comment by rtripault** [comment]
Indeed.

Would you mind removing that return statement https://github.com/meltingmedia/Vertical-Navigation/blob/master/assets/js/vertical-menu.js#L421 and try again please ? (making sure you cleared your browser cache)

**Comment by mcnickel** [comment]
Done! Fixed! Even without clearing the browser cache ;)

**Comment by rtripault** [comment]
:+1:  so closing.

Thanks
